# Generated by Django 5.2.8 on 2025-11-08 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light'), ('custom', 'Custom')], default='dark', max_length=20)),
                ('theme_custom_colors', models.JSONField(blank=True, default=dict)),
                ('ai_response_length', models.CharField(choices=[('short', 'Short'), ('medium', 'Medium'), ('long', 'Long')], default='medium', max_length=20)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('notification_sound', models.BooleanField(default=True)),
                ('notification_position', models.CharField(choices=[('top-left', 'Top Left'), ('top-right', 'Top Right'), ('bottom-left', 'Bottom Left'), ('bottom-right', 'Bottom Right')], default='bottom-right', max_length=20)),
                ('window_default_x', models.IntegerField(default=100)),
                ('window_default_y', models.IntegerField(default=100)),
                ('window_default_width', models.IntegerField(default=400)),
                ('window_default_height', models.IntegerField(default=600)),
                ('window_opacity', models.FloatField(default=0.95)),
                ('voice_enabled', models.BooleanField(default=True)),
                ('preferred_voice', models.CharField(choices=[('alloy', 'Alloy'), ('echo', 'Echo'), ('fable', 'Fable'), ('onyx', 'Onyx'), ('nova', 'Nova'), ('shimmer', 'Shimmer')], default='alloy', max_length=20)),
                ('voice_speed', models.FloatField(default=1.0)),
                ('voice_language', models.CharField(default='en-US', max_length=10)),
                ('total_tokens_used', models.BigIntegerField(default=0)),
                ('current_month_tokens', models.IntegerField(default=0)),
                ('current_day_tokens', models.IntegerField(default=0)),
                ('daily_token_limit', models.IntegerField(default=10000)),
                ('monthly_token_limit', models.IntegerField(default=100000)),
                ('last_reset_date', models.DateField(auto_now_add=True)),
                ('is_premium_user', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
