# Generated by Django 5.2.8 on 2025-11-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='daily_token_limit',
            field=models.IntegerField(default=100000),
        ),
    ]
