# Generated by Django 5.2.8 on 2025-11-08 05:42

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('feature_type', models.CharField(choices=[('chat', 'Chat'), ('summarize', 'Summarize'), ('translate', 'Translate'), ('explain_code', 'Explain Code'), ('voice_transcribe', 'Voice Transcription'), ('voice_tts', 'Text-to-Speech')], db_index=True, max_length=50)),
                ('ai_model_used', models.CharField(max_length=100)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=Decimal('0.0'), max_digits=10)),
                ('request_count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token Usage',
                'verbose_name_plural': 'Token Usage Records',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='token_usage_user_id_60c78c_idx'), models.Index(fields=['user', 'feature_type'], name='token_usage_user_id_ab472b_idx'), models.Index(fields=['date', 'feature_type'], name='token_usage_date_8babde_idx')],
            },
        ),
        migrations.CreateModel(
            name='UsageQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota_type', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('lifetime', 'Lifetime')], db_index=True, max_length=20)),
                ('limit', models.IntegerField()),
                ('used', models.IntegerField(default=0)),
                ('reset_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usage Quota',
                'verbose_name_plural': 'Usage Quotas',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'quota_type')},
            },
        ),
    ]
