# Generated by Django 5.2.8 on 2025-11-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_interactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='image_mime_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='image_size',
            field=models.IntegerField(blank=True, help_text='Image file size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
