# Generated by Django 5.2.8 on 2025-11-08 15:54

import config.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_interactions', '0002_aimessage_image_aimessage_image_mime_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimessage',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=config.storages.MinIOChatMediaStorage(), upload_to='chat_images/'),
        ),
    ]
