# Generated by Django 5.2.8 on 2025-11-08 05:46

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('transcribed_text', models.TextField()),
                ('command_type', models.CharField(choices=[('question', 'Question'), ('action', 'Action'), ('translate', 'Translate'), ('summarize', 'Summarize')], max_length=50)),
                ('response_text', models.TextField(blank=True)),
                ('stt_method', models.CharField(choices=[('backend_whisper', 'Backend Whisper'), ('frontend_webspeech', 'Frontend Web Speech'), ('manual_text', 'Manual Text')], max_length=50)),
                ('audio_duration', models.FloatField(blank=True, null=True)),
                ('transcription_tokens', models.IntegerField(default=0)),
                ('tts_characters', models.IntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=6, default=Decimal('0.0'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_commands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voice Command',
                'verbose_name_plural': 'Voice Commands',
                'ordering': ['-created_at'],
            },
        ),
    ]
